---
title: '2018-11-07'
output: html_document
---

```{r}
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```

```{r}
民國年月<-c("099/01","099/02","099/03")

library(lubridate)
library(stringr)
library(dplyr)
# 1
民國年月 %>%     
  str_c("1", . ,"/01") %>%
  ymd %>%
  { . + years(911) }
# 1.把民國年月丟到.的位置（因為民國年月不是在第一個位置，或是唯一一個，所以用.代替），可以不用暫存，又被丟到下一行執行程式；2.%>%---是把上一個程式結果直接丟到一行的程式；3.如果要往下丟的步驟不是函數，則用{.}把運算式子括起來，並以.代替上一行的答案。
```

```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
```
```{r}
library(dplyr)
mutate(
  collegeData, #資料集
  學校代碼=as.factor(學校代碼), #要處理的變數(=右邊是要處理的方式)
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2
```

```{r}
#舊寫法
as.factor(collegeData$學校代碼)->collegeData$學校代碼
as.factor(collegeData$學校名稱)->collegeData$學校名稱
```

```{r}
collegeData %>%
  mutate(
  . , #沒有.也可以運作
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2
```
```{r}
collegeData %>%
  mutate(
    學校代碼=as.factor(學校代碼),
    學校名稱=as.factor(學校名稱)
  )
#資料集變成data.frame
```

```{r}
collegeData %>%
  mutate(
         `日間∕進修別`=as.factor(`日間∕進修別`),
         等級別=as.factor(等級別),
         一年級男生=as.numeric(一年級男生),
         一年級女生=as.numeric(一年級女生)
         )->collegeData2
```
```{r}
#要將character class轉成不同class，雖然可以用as.XXX(), XXX為class name, 但它有時會判斷失敗，而把該筆資料轉成NA。（因為有， 所以辨別不出數字）
library(stringr)
collegeData %>%
  mutate(
    一年級男生=str_replace_all(一年級男生,",",""),
    一年級女生=str_replace_all(一年級女生,",","")
  ) %>%
  mutate( #可以不用在%>% mutate一次，直接在上一個mutate就完成
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  )->collegeData3
```

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl), #parse_number---會產生後面有problem的紀錄
    一年級女生=parse_number(一年級女生,locale=locale(grouping_mark = ","))
  ) -> collegeData4
```

```{r}
problems(collegeData4$一年級男生)
#檢視parse_number找到的問題：看得到轉不出的項目，有紀錄下原來的資料是-
```


```{r}
library(readr)
cl<-locale(grouping_mark = ",")
collegeData %>%
  mutate(
      一年級男生=parse_number(一年級男生,na=c("","NA","-"),locale = cl),
      一年級女生=parse_number(一年級女生,na=c("","NA","-"),locale = cl),
      二年級男生=parse_number(二年級男生,na=c("","NA","-"),locale = cl),
      二年級女生=parse_number(二年級女生,na=c("","NA","-"),locale = cl)
  )->collegeData4

#na=c("","NA","-") 忽略這些東西
```

```{r}
collegeData %>%
  select(一年級男生,一年級女生,二年級男生,二年級女生)->college1stYearData
library(stringr)
college1stYearData %>%
  mutate_all(funs(parse_number(.,na=c("","NA","-"),locale=cl))) ->
  college1stYearDataNumeric

#funs所有要做的事
college1stYearDataNumeric
```
```{r}
college1stYearDataNumeric %>%
  mutate_all(
    funs(
      每百人=./100,
      每千人=./1000
    )
  )->college1stYearDataNumeric
college1stYearDataNumeric

college1stYearDataNumeric %>% colnames
```

```{r}
collegeData %>% 
  mutate_at( #只對選出的變數做改變
  vars(一年級男生,一年級女生), #選出變數
  funs(parse_number(.,locale=cl))
) -> college1stYearDataA

college1stYearDataA %>%
  select(一年級男生,一年級女生)
```

```{r}
collegeData %>%
  mutate_at(
    vars(
      contains("生")
    ),
    funs(
      parse_number(.,na =c("","NA","-"),locale = cl)
    )
  ) %>%
   mutate_at(
    vars(
      contains("學")
    ),
    funs(as.factor(.))
  )->collegeData4

```


#homework try

```{r}
x <- c(0:10, 50)
mean(x)
c(mean(x), mean(x, trim = 0.10))
#tim=0.1----先把最大的10%和最小10%的數去掉，在算平均

```
```{r}
sum(1, 2, 3, 4, 5)

sum(1:5)

sum(1:2, 3:5)

sum(1:5, NA, na.rm = TRUE)
```
```{r}
fruit <- c("apple", "banana", "pear", "pinapple")
str_which(fruit, "e")#選出要的東西的位置
```
```{r}
x <- cbind(x1 = 3, x2 = c(4:1, 2:5))
rowSums(x)
```

```{r}
which(1:10 > 3, arr.ind = TRUE)
```
```{r}
fruit <- c("apple", "banana", "pear", "pineapple")
str_locate(fruit, "a")
```
```{r}
m2 <- cbind(1, 1:4)
colnames(m2) <- c("x","Y")
```

