---
title: '2018-12-26'
output: html_document
---

```{r}
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
library(readr)
```


```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo = TRUE)
```
 

```{r}
 library(readr); library(dplyr); library(stringr); library(lubridate)
```
 
#Object extraction,範例plotly
```{r}
 install.packages("plotly")
```

```{r}
download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda
```
```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity <-0.7 #opacity-不透明度
plotly_4070_neda
```

```{r}
plotly_4070_neda$x$layout$shapes[[1]]$fillcolor <- "ACFA58"
plotly_4070_neda
```

#list example
##vector
```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcript100_102.csv",
                  col_types = cols(
                    學期成績="n"
                  ))

totalCredits<-function(x){
  transcriptData[transcriptData$學號==x,]->subsample 
  subsample %>%
    mutate(
      及格=(學期成績>=60)
    ) %>%
    summarise(
      學號=學號[1],
      總修習學分數=sum(學分數),
      總實得學分數=sum(學分數[及格])
    )  
}
```
```{r}
#計算學屆為100、學系為“P1”的所有學生「總修習學分數」及「總實得學分數」
transcriptData %>%
  filter(學屆==100,str_sub(學號,5,6)=="P1") -> subsample
subsample$學號 %>% unique -> 符合條件學號 
#unique 把重複的刪掉，留下沒有重複的數據
```

```{r}
creditResults<-vector("list",length(符合條件學號))
```

```{r}
for(i in seq_along(符合條件學號)){
  creditResults[[i]] <- totalCredits(符合條件學號[i])
} #跑完後，所有符合條件的學號都會在裡面

creditResults[[109]]

#一下是i=1的處理方式
i<-1
#1
符合條件學號[i]
#2
totalCredits(符合條件學號[i])
#3
creditResults[[i]] <- totalCredits(符合條件學號[i])


```

##Nested data frame
```{r}
library(readr)
library(tidyr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/libraryData2.csv")
```

```{r}
libraryData %>%
  filter(學院=="人文學院")
```

```{r}
libraryData %>%
  group_by(學院) %>%
  nest -> nestLibraryData #tibble is data.frame,nestLibraryData 類似libraryData 以學院為分類的目錄

nestLibraryData %>%
  filter(學院=="人文學院") %>%
  .$data
```


```{r}
libraryData %>%
  group_by(學院) %>%
  nest(.key="各院借閱資料") ->
  libraryDataNested


libraryDataNested %>%
  filter(學院=="人文學院") %>%
  .$各院借閱資料
```

```{r}
#8.6.2.1
#計算每位學生（即每個學號）「各學年」的學年總借閱冊數。 
libraryData %>%
  group_by(學號,學年) %>%
  summarise(
    學年總借閱冊數=n()
  ) -> libraryData2
```

##str_split()
```{r}
library(dplyr)
df <- data.frame(
  x = 1:3,
  y = c("a", "d,e,f", "g,h"),
  stringsAsFactors = F
)
df %>%
  mutate(y = str_split(y, ",")) -> dfSplit

```


