---
title: "2018-10-31"
output: html_document
---

```{r cars}
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```

```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
names(StuDF)

names(gsSurvey) #gsSurvey底下有的項目資料名稱
```
```{r}
gsSurvey$links$type #因為type為最後一層資料，所以會變成一維，如要在取出，需用c（）來做
```

```{r}
names(StuDF)[2] <- c("姓名") #只改原表中項目2(use [ ] )的名字
names(StuDF)
```

```{r}
names(StuDF) <- c("學號","姓名","成績") #改變原表中項目的名字
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距)
levels(student$身高級距)[1:5] <- c("小個子")
levels(student$身高級距)[6:7] <- c("中等個字")
levels(student$身高級距)[8:9] <- c("高個子")
levels(student$身高級距)
```



```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```
```{r}
levels(student$身高級距) #找出有的組合名稱
levels(student$身高級距)[c(1:3)]<-c("(0,160]")
#將上一行列出的級距（1到3個）換成（0，160]

```

###課堂練習

```{r} 
#1.1
dim(classSurvey)  #dimension,每個維度有多少變數
```

```{r} 
#1.2
stringr::str_sub(classSurvey$學號,2,4)->classSurvey$年級
 #分辨入學年
as.factor(classSurvey$年級)->classSurvey$年級
#把factor變成data.frame
levels(classSurvey$年級) #將有的入學年組合名稱列出
levels(classSurvey$年級)<-c("大四及以上","大三","大二","大一")
#先看levels(classSurvey$年級)再來依先後順序轉名字

```

```{r}
#1.3

```


```{r}
#1.6
(classSurvey$年級 == "大一")->newActivity
classSurvey[newActivity,8]->newActivity
stringr::str_split_fixed(newActivity$本學期目前已參加之課外活動,", ",n=2)->newActivity1
stringr::str_c(newActivity1)->newActivity1 #從矩陣拆成factor
table(newActivity1)
```

