---
title: '2018-10-03'
output: html_document
---

```{r}
library(lubridate)
a <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="month")
b <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="quarter")
c <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="year")
##seq(start,end),by=增加的內容
```

#str_sub(把要的vector從資料中叫出)
```{r}
library(readr)
studentID <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/studentID.csv")

```

```{r}
library(stringr)
str_sub(studentID$學號,5,6)->classID#str_sub(資料,start=第幾個,end=第幾個)
table(classID)#分門別類後各個類別的人數
```

#str_c
```{r}
?str_c
```
```{r}
letters
```
```{r}
LETTERS
```

```{r}
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
```
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
```
```{r}
githubData[c(2,3,4),] -> sampleGithub #[c(2,3,4),]是2、3、4列（橫的）的所有行數資料（因為，後面沒數字）
str_c(sampleGithub$`GitHub username`,
      sampleGithub$`GitHub repo name`)
str_c("https://github.com/",
      sampleGithub$`GitHub username`,
      "/",
      sampleGithub$`GitHub repo name`)
```

#str_split_fixed()
```{r}
?str_split_fixed
```
```{r}
fruits <- c(
  "apples and oranges and pears and bananas",
  "pineapples and mangos and guavas"
) #2 elements

str_split(fruits, " and ")#個別斷2個elements
str_split(fruits, " and ", simplify = TRUE)

# Use fixed to return a character matrix
str_split_fixed(fruits, " and ", 3)#change to [2*3]矩陣,element1切成3斷
str_split_fixed(fruits, " and ", 4)#change to [2*4]矩陣

```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
```
```{r}
str_split_fixed(filmVotingData$請選擇你最喜歡的影片二部,",",3)->bb
dim(bb)

cc<-c(bb)
table(cc)
```
#taiwan date-time
```{r}
民國年月<-c("099/01","099/02","099/03")
str_c()
str_c(lubridate::民國年月 + years(911) )

```





