---
title: '2018-10-24'
output: html_document
---
#pratice
```{r}
library(googlesheets)#gs_auth(new_user = TRUE)
```
```{r}
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```


```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1,locale=readr::locale(encoding = "UTF-8")) #access the 1st worksheet

library(readr)
classSurvey<-read.csv("classSurvey.csv")
```
```{r}
library(readr)
classSurvey<-read.csv("classSurvey.csv",header = TRUE,fileEncoding = "UTF-8")
View(classSurvey)
```




```{r}
head(classSurvey,10) #10——到第10筆
```

```{r}
names(classSurvey) #兩個都一樣的意思
colnames(classSurvey)
```
```{r}
row.names(classSurvey)
```




#class---Data Frame
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50),
  stringsAsFactors = F #不要字串進來就變成factor
  )
StuDF 
```
#1.names
```{r}
names(StuDF) 
colnames(StuDF) #列的名稱
```
```{r}
row.names(StuDF) #行的名稱
```
```{r}
StuDF[1,2] #取第一個row的第二個值，即（1，2）的值
StuDF[,2] #空白，即不選
StuDF[1,]
StuDF[c(1,4),] #選1 & 4整行的值，因為column沒有設定
StuDF[c(1,4),c(2,3)] #選1 & 4的2、3列的值
```
```{r}
StuDF[c(1,2,3),]
StuDF[c(1:3),] #：取1到3行的值
StuDF[c(1:3,5),]
```

#2.numerical/logical index
#  matrix index
```{r}
StuDF[c(1,4),]
StuDF[-c(1,4),] #非1、4 整行的值（因為有"-"）
```
#  true/false
```{r}
StuDF[c(T,F,F,F,F),c(F,T,F)] #另一種方式叫數據進來，T(true)-in，F(false)-not in
StuDF[c(T,F,F,T,F),]
```
```{r}
a<-c(T,T,F,F,T,F,F)
sum(a) #加總
```
```{r}
StuDF[c(T,F,F,F,F),] #同StuDF[1,]
```
```{r}
StuDF[c(T,F,F,T,F),c(F,T,T,F,F)] #同StuDF[c(1,4),c(2,3)]
```
#Relational operators
```{r}
(StuDF$score >= 80)->aa
(StuDF$name == "小新")->ab
```
```{r}
StuDF[c(aa),c(T,T,F)] #>=80的名字
StuDF[c(aa),c(1,2)]
```
```{r}
StuDF[c(ab),3] #小新的成績
StuDF[which(StuDF$name == "小新"),] #迴圈StuDF$name找到"小新"的T/F
```

```{r}
which(StuDF$score >= 80)
which(StuDF$name == "小新")
```

#Logical operators
```{r}
(classSurvey$性別 == "男")->bb

(classSurvey$本學期學分數 > 20)->cc

(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)->dd
cbind(bb,cc,dd) #將上述分成bb，cc，dd列出判斷
```
```{r}
(classSurvey$性別 == "男" & classSurvey$本學期學分數 > 26)->people
classSurvey[c(people),3]

stringr::str_sub(classSurvey$居住地行政區,1,3)->peopleTaipei
classSurvey[peopleTaipei == "台北市",3]

stringr::str_sub(classSurvey$居住地行政區,1,3)->peopleNewTaipei
classSurvey[peopleTaipei == "新北市",3]

(classSurvey$居住地行政區 == "新北市三峽區")->peopleNewTaipei
classSurvey[peopleNewTaipei,3]   #?why not
```

```{r}
StuDF$StuID
StuDF[,c("StuID")]
StuDF$name
StuDF[,c("name")]

StuDF[,c("StuID","name")]
## 無法用$一次取兩個元素
# StuDF$c("StuID","name")
```

```{r}
StuDF[c(1,4),c(2)]
StuDF[,c(2)][c(1,4)] 
## 前面先選出第2列的所有值，出來變一維的東西；後面再從一維的答案，選出1、4的元素
StuDF[,c(2)] -> aa
aa[c(1,4)] 
```

```{r}
StuDF[,c(1,3)][c(1,4),]
```

