---
title: "pratice1(class-20180926)"
output: html_document
---

#Factor(levels,table),Numeric,Character
```{r}
?factor #系列變數
```
```{r}
gender <- c("男性", "男性", "女性", "男性", "女性", "男性")
as.factor(gender)
factor(gender,levels = c("男性", "女性"),labels = c("Male","Female"))
```

```{r}
?numeric #數字
```
```{r}
as.numeric(c("-.1"," 2.7 ","B")) # (-0.1, 2.7, NA)  +  warning
#將c（）裡的東西轉換成數字型態
```


```{r}
?character #字符
```
```{r}
form <- y ~ a + b + 1
as.character(form)  ## length 3
deparse(form)       ## like the input
```



```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
as.factor(student$入學年)->student$入學年
```

```{r}
levels(student$入學年) #入學年的類別
```
```{r}
nlevels(student$入學年)#入學年類別的個數
```


```{r}
table(student$入學年)#各個入學年的人數
```
```{r}
as.factor(student$性別)->student$性別
```
```{r}
levels(student$性別)
```
```{r}
table(student$性別)
```

```{r}
as.factor(student$身高)->student$身高
```
```{r}
levels(student$身高)
```
```{r}
table(student$身高)
```

```{r}
as.factor(student$出生地)->student$出生地
```
```{r}
nlevels(student$出生地)
```


#Date and Time

```{r}
library(dplyr)
library(lubridate)
a <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="month")
b <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="quarter")
c <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="year")
#依by=?來編輯出一個序列，例如a就是依月來編輯序列，所以序列的各式(format)是2001-01-01、2001-02-01···
```

#C
```{r}
?c
```
```{r}
?head

```
```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
head(student,n = 10L)
```

